using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;
using System.Threading;
using System;
using UnityEngine.Events;
using System.Net;
using System.Net.Sockets;
using UnityEngine.UI;
using System.Text;
using System.Collections.Concurrent;
using UnityEngine.SceneManagement;
using UnityEngine.Audio;
public class GameManager : MonoBehaviour
{
    //cama
    int fi = 0;
    public AudioSource Voice = null;
    public AudioClip[] VoiceClips = null;
    //int game = mode_num.mode;
    public string IP ;
    public int Port ;
    public int mode_int = 0;
    public Socket client;
    int i = 0;
    string msg = "";
    string pose = "";
    int now_cnt = Gobal_TCP.text_cnt;
    int winner;

    //file text write
    string path = @"d:\å¤§å­¸\onlyPSS\onlyPSS\\test1.txt";
	string[] createText = {""};

    static GameManager instance;
    //TCP so0cket ï¿½hï¿½ï¿½ï¿½ï¿½
    void Awake()
    {
        if (instance == null)
        {
            instance = this;
            DontDestroyOnLoad(this);
            name = "first_game";
        }
        else if (this != instance && instance != null)
        {
            string ScenName = SceneManager.GetActiveScene().name;
            Debug.Log("ï¿½Rï¿½ï¿½" + ScenName + "ï¿½ï¿½" + name);
            Destroy(gameObject);
        }

    }
    /// <summary>
    /// ////////////////////////////////////////////////////////
    /// </summary>
    //ï¿½Nserverï¿½ï¿½ï¿½eï¿½ï¿½sï¿½Wï¿½h
    void Update()
    {
        /*//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if (Gobal_TCP.game_mode == 0)
        {
            SceneManager.LoadScene(0);
            Debug.Log("switch Sence 0 (UI)");
        }
        else if (Gobal_TCP.game_mode == 1)
        {
            SceneManager.LoadScene(1);
            Debug.Log("switch Sence 1 (PSS Game)");
        }
        else if (Gobal_TCP.game_mode == 2)
        {
            SceneManager.LoadScene(2);
            Debug.Log("switch Sence 2 (Dance Game)");
        }*/
        //ï¿½ï¿½ï¿½yï¿½Å¤Mï¿½ï¿½ï¿½Yï¿½ï¿½
        if (varName.cnt_end)
        {
            //ï¿½iï¿½Dserverï¿½iï¿½Hï¿½ï¿½
            client.Send(Encoding.UTF8.GetBytes("shot;"));
            varName.cnt_end = false;


        }
        if (varName.game1Over && fi==0)//ï¿½iï¿½Dserverï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        {
            client.Send(Encoding.UTF8.GetBytes("over;"));
            //fi = 1;
            varName.game1Over = false;
        }
        if (Gobal_TCP.game2Over && fi == 0)//ï¿½iï¿½Dserverï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        {
            client.Send(Encoding.UTF8.GetBytes("over2;"));
            //fi = 1;
            Gobal_TCP.game2Over = false;
        }

    }
    //ï¿½Ø¥ß³sï¿½u
    void Start()
    {
        Debug.Log("hi" + i);
        i++;
        client = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
        client.Connect(IP, Port);
        Thread t = new Thread(recvData);
       
        t.Start();
        

    }
    /*void recvIMG()
    {
        Debug.Log("recvIMG start");
        while (client.Connected)
        {
            
            var bytes = new byte[1024];
            var count = client.Receive(bytes);
            float dis;
            msg = Encoding.UTF8.GetString(bytes, 0, count);
            //ï¿½ï¿½ï¿½ï¿½ scale;123456
            string[] msg_split = msg.Split(';');
            //Debug.Log("ï¿½ï¿½ï¿½ï¿½" + msg);
           // Debug.Log("msg[0]" + msg_split[0]);
            //Debug.Log("msg[1]" + msg_split[1]);


            if (msg != null)
            {
                //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½openpose ï¿½ï¿½ ï¿½^ï¿½Ç¸ï¿½ï¿??
                if (msg_split[0] == "scale")
                {
                    //Debug.Log("scaleï¿½ï¿½" + msg_split[1]);
                    dis = (Convert.ToInt32(msg_split[1]));
                    //Debug.Log("scaleï¿½ï¿½(dis)" + dis);
                    varName.img_dis = dis;
                }


            }

        }
       
    }*/
    //ï¿½jï¿½é¦¬ï¿½ï¿½ï¿??
    void recvData()
    {
        int im = 1;
        //ï¿½iï¿½ï¿½ï¿½Ounity ï¿½ÝªO
        client.Send(Encoding.UTF8.GetBytes("1"));

        // Thread t_img = new Thread(recvIMG);
        //t_img.Start();
        float dis;
        while (client.Connected)
        {


            //ï¿½ï¿½ï¿½ï¿½Tï¿½ï¿½ï¿½dï¿½ï¿½ : text;welcome
            var bytes = new byte[1024];
            var count = client.Receive(bytes);
            msg = Encoding.UTF8.GetString(bytes, 0, count);
            //ï¿½ï¿½ï¿½ï¿½
            string[] msg_split = msg.Split(';');
            //Debug.Log("ï¿½ï¿½ï¿½ï¿½" + msg);
            //Debug.Log("msg[0]" + msg_split[0]);
            //Debug.Log("msg[1]" + msg_split[1]);

            
            if (msg != null)
            {
                if (msg_split[0] == "text")
                {
                    pamadan(msg_split[1]);
                }
                else if(msg_split[0] == "game1")
                {
                    Debug.Log("ï¿½ï¿½ï¿½ï¿½game1");
                    loadToPSS();
                }
                else if (msg_split[0] == "game2")
                {
                    Debug.Log("ï¿½ï¿½ï¿½ï¿½game2");
                    loadToDance();
                }

                //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½openpose ï¿½ï¿½ ï¿½^ï¿½Ç¸ï¿½ï¿??
                if (msg_split[0]=="pose")
                {
                    Debug.Log("Scanï¿½ï¿½ï¿½G" + msg_split[1]);
                    //ï¿½Ò°ï¿½modelï¿½ï¿½ï¿½ï¿½ï¿½wï¿½Ê§@
                    
                    //ï¿½Pï¿½_ï¿½ï¿½Ä¹
                    whoWin(msg_split[1]);
                }                
                if (msg_split[0] == "scale")
                {
                    //Debug.Log("scaleï¿½ï¿½" + msg_split[1]);
                    dis = (Convert.ToInt32(msg_split[1]));
                    //Debug.Log("scaleï¿½ï¿½(dis)" + dis);
                    varName.img_dis = dis;
                }
                //(ï¿½|ï¿½ï¿½)ï¿½ï¿½ï¿½ï¿½nï¿½}ï¿½lï¿½ï¿½ï¿½R
                if (msg_split[0] == "handup")
                {
                    Debug.Log("handup!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
                    Gobal_TCP.handup = true;
                }
                //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½ï¿½ï¿½ï¿½
                if (msg_split[0] == "Dcore")
                {
                    Debug.Log("Dcore!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
                    string str  = msg_split[1];
                    //Gobal_TCP.Dcore = (Convert.ToInt32(str));
                    Debug.Log("Dcore=!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
                }
                ///ï¿½ï¿½ï¿½ï¿½ï¿½`ï¿½Iï¿½ï¿½ï¿??
                if (msg_split[0] == "k")
                {
                    //file text write
                    if(Gobal_video.status == 1 && Gobal_video.timeFlag == 1) {
                        string appendText = msg + Environment.NewLine;
                        // print(msg);
                        File.AppendAllText(path, appendText, Encoding.UTF8);
                        Gobal_video.timeFlag = 0;
                        // print("gameManage second");
                    }

                    //Debug.Log("ï¿½ï¿½ï¿½`ï¿½I" + msg);
                    string[] sArray = msg.Split(';');
                    Gobal_TCP.leftShoulderPos.x = float.Parse(sArray[1]);
                    Gobal_TCP.leftShoulderPos.y = float.Parse(sArray[2]);
                    Gobal_TCP.leftShoulderPos.z = float.Parse(sArray[3]);
                    Gobal_TCP.leftForeArmPos.x = float.Parse(sArray[4]);
                    Gobal_TCP.leftForeArmPos.y = float.Parse(sArray[5]);
                    Gobal_TCP.leftForeArmPos.z = float.Parse(sArray[6]);
                    Gobal_TCP.leftHandPos.x = float.Parse(sArray[7]);
                    Gobal_TCP.leftHandPos.y = float.Parse(sArray[8]);
                    Gobal_TCP.leftHandPos.z = float.Parse(sArray[9]);

                    Gobal_TCP.headPos.x = float.Parse(sArray[10]);
                    Gobal_TCP.headPos.y = float.Parse(sArray[11]);
                    Gobal_TCP.headPos.z = float.Parse(sArray[12]);
                    Gobal_TCP.neckPos.x = float.Parse(sArray[13]);
                    Gobal_TCP.neckPos.y = float.Parse(sArray[14]);
                    Gobal_TCP.neckPos.z = float.Parse(sArray[15]);
                    Gobal_TCP.spine2Pos.x = float.Parse(sArray[16]);
                    Gobal_TCP.spine2Pos.y = float.Parse(sArray[17]);
                    Gobal_TCP.spine2Pos.z = float.Parse(sArray[18]);

                    Gobal_TCP.rightShoulderPos.x = float.Parse(sArray[19]);
                    Gobal_TCP.rightShoulderPos.y = float.Parse(sArray[20]);
                    Gobal_TCP.rightShoulderPos.z = float.Parse(sArray[21]);
                    Gobal_TCP.rightForeArmPos.x = float.Parse(sArray[22]);
                    Gobal_TCP.rightForeArmPos.y = float.Parse(sArray[23]);
                    Gobal_TCP.rightForeArmPos.z = float.Parse(sArray[24]);
                    Gobal_TCP.rightHandPos.x = float.Parse(sArray[25]);
                    Gobal_TCP.rightHandPos.y = float.Parse(sArray[26]);
                    Gobal_TCP.rightHandPos.z = float.Parse(sArray[27]);

                    Gobal_TCP.leftupLegPos.x = float.Parse(sArray[28]);
                    Gobal_TCP.leftupLegPos.y = float.Parse(sArray[29]);
                    Gobal_TCP.leftupLegPos.z = float.Parse(sArray[30]);
                    Gobal_TCP.leftLegPos.x = float.Parse(sArray[31]);
                    Gobal_TCP.leftLegPos.y = float.Parse(sArray[32]);
                    Gobal_TCP.leftLegPos.z = float.Parse(sArray[33]);
                    Gobal_TCP.leftFootPos.x = float.Parse(sArray[34]);
                    Gobal_TCP.leftFootPos.y = float.Parse(sArray[35]);
                    Gobal_TCP.leftFootPos.z = float.Parse(sArray[36]);

                    Gobal_TCP.rightupLegPos.x = float.Parse(sArray[37]);
                    Gobal_TCP.rightupLegPos.y = float.Parse(sArray[38]);
                    Gobal_TCP.rightupLegPos.z = float.Parse(sArray[39]);
                    Gobal_TCP.rightLegPos.x = float.Parse(sArray[40]);
                    Gobal_TCP.rightLegPos.y = float.Parse(sArray[41]);
                    Gobal_TCP.rightLegPos.z = float.Parse(sArray[42]);
                    Gobal_TCP.rightFootPos.x = float.Parse(sArray[43]);
                    Gobal_TCP.rightFootPos.y = float.Parse(sArray[44]);
                    Gobal_TCP.rightFootPos.z = float.Parse(sArray[45]);

                    //print("Gobal_TCP.leftShoulderPos" + Gobal_TCP.leftShoulderPos);
                    // print("Gobal_TCP.leftForeArmPos" + Gobal_TCP.leftForeArmPos);
                    // print("Gobal_TCP.rightFootPos" + Gobal_TCP.rightFootPos);
                    // print("Gobal_TCP.leftFootPos" + Gobal_TCP.leftFootPos);
                }

            }else
            {
                client.Close();
            }

        }
    }
    ////ï¿½Pï¿½_ï¿½ï¿½Ä¹
    void whoWin(string pose)
    {
        //1st: player 2nd:model
        string[] P = pose.Split(' ');
        string player = P[0];
        string model = P[1] ;
        
        
        //winner : 0=ï¿½ï¿½ï¿½ï¿½, 1=model, 2=player
        //modelï¿½Xï¿½Å¤M
        if (model == "1")
        {
            varName.modelPose = "ï¿½Å¤M Scissor";
            if (player == "1")
            {
                varName.playerPose = "ï¿½Å¤M Scissor";
                varName.winner = 0;
            }
                
            else if (player == "2")
            {
                varName.winner = 2;
                varName.playerPose = "ï¿½ï¿½ï¿½Y Stone";

            }
            else
            {
                varName.winner = 1;
                varName.playerPose = "ï¿½ï¿½ Paper";

            }
        }
        //modelï¿½Xï¿½ï¿½ï¿½Y
        else if (model == "2")
        {
            varName.modelPose = "ï¿½ï¿½ï¿½Y Stone";
            if (player == "1")
            {
                varName.winner = 1;
                varName.playerPose = "ï¿½Å¤M Scissor";

            }
            else if (player == "2")
            { 
                varName.winner = 0;
                varName.playerPose = "ï¿½ï¿½ï¿½Y Stone";
            }
            else
            {
                varName.winner = 2;
                varName.playerPose = "ï¿½ï¿½ Paper";
            }
        }
        //modelï¿½Xï¿½ï¿½
        else if (model == "3")
        {
            varName.modelPose = "ï¿½ï¿½ Paper";
            if (player == "1")
            {
                varName.winner = 2;
                varName.playerPose = "ï¿½Å¤M Scissor";
            }
            else if (player == "2")
            {
                varName.winner = 1;
                varName.playerPose = "ï¿½ï¿½ï¿½Y Stone";
            }
            else
            {
                varName.winner = 0;
                varName.playerPose = "ï¿½ï¿½ Paper";

            }
        }
        Debug.Log("winner=" + varName.winner);
        //1.ï¿½ï¿½modelï¿½ï¿½ï¿½ï¿½ï¿½wï¿½Ê§@
        varName.model_start_animation = true;


    }
    void loadToPSS()
    {

        varName.mode = 1;
    }
    void loadToDance()
    {
        varName.mode = 2;
    }
    //--UI--ï¿½]ï¿½ï¿½ï¿½O
    void pamadan(string content)
    {
        Debug.Log("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!PamaDan center = " + content);
       
        Debug.Log("Gobal_TCP.text_cnt = " + Gobal_TCP.text_cnt);
        if (Gobal_TCP.text_cnt == now_cnt)
        {
           if (Gobal_TCP.text_cnt % 2 == 0)
                {
                    Gobal_TCP.text1 = content;
                    Gobal_TCP.text_cnt++;
                    now_cnt = Gobal_TCP.text_cnt;
                }
                else if (Gobal_TCP.text_cnt % 2 == 1)
                {
                    Gobal_TCP.text2 = content;
                    Gobal_TCP.text_cnt++;
                    now_cnt = Gobal_TCP.text_cnt;
                }
        }
     
    }




}